default_language_version:
  python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: tests/.*|docker/.*
    -   id: end-of-file-fixer
        exclude: tests/.*|docker/.*
    -   id: check-yaml
    -   id: check-added-large-files


-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        exclude: tests/.*

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3
        exclude: tests/.*|docker/.*

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.11.10'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: tests/.*|docker/.*


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic, pydantic-settings, sqlalchemy]
        exclude: tests/.*|docker/.*
fail_fast: true
