#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE "$POSTGRES_TEST_NAME";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_TEST_NAME" TO "$POSTGRES_USER";
EOSQL